# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Matthew Aiello-Lammens
tagline:             'Ecologist at Work'
description:         'The website of Matt Aiello-Lammens'
url:                 
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Matthew Aiello-Lammens
  url:               
  email:             matt.lammens@gmail.com

