# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Matthew Aiello-Lammens
tagline:             'Ecologist at Work'
description:         'Matt Aiello-Lammens - Information and random thoughts'
url:                 
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Matthew Aiello-Lammens
  url:               
  email:             matt.lammens@gmail.com

