baseurl = "/"
languageCode = "en-us"
title = "Personal website for Matt Aiello-Lammens"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Writing Log"
    url = "/writing/"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; Matthew E. Aiello-Lammens 2014 -- 2021 | [Github](https://github.com/mlammens) | [Twitter](https://twitter.com/MattLammens)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true