---
output:
  md_document:
    variant: markdown_github
---

My current research involves working with a number of colleagues who 
are studying the trait by environment (tXe) relationshinps (and evolutionary 
histories) of members of the genera *Protea* and *Pelargonium*, 
while I and a few others look at tXe for whole communities. 
In a [recent AmNat paper](http://www.jstor.org/stable/10.1086/680051), a few
members of our group showed that there appear to be very clear tXe relationhsips
throughout the CFR for the two focal genera. What's more, they found that 
in a number of cases, the tXe relationship is significantly different between
*Protea* and *Pelargonium*. For example, plant size is negativelly associated
with drought duration for proteas and possitively associated for pelargonium.
Yet, members of these genera co-occur in many of the community plots we are
examining. So if we look at the community average size versus drought duration
in a plot comprised of proteas and pelies, we may very well find a flat 
relationship, concluding that at the community level, size is not associated
with drought. This is a classic example of a problem sometimes referred to as 
**the ecolgical fallacy**.